PROGRAM MASTER

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

INTEGER(KIND=JPIM) :: IRANK, ISIZE

CHARACTER*32 :: CLBIND

CALL GETENV ('LLBIND', CLBIND)

IRANK = 0
ISIZE = 1

!IF (CLBIND == '1') CALL LINUX_BIND (IRANK, ISIZE)

CALL SPCMSI2


CONTAINS

SUBROUTINE SPCMSI2

IMPLICIT NONE

INTEGER :: ISTA

CHARACTER*32 :: CLENV

REAL(8) :: TIME_START,TIME_END

call get_time(time_start)
CALL SPCSI2

CALL GETENV ('LLOMP', CLENV)

IF (CLENV == '1') THEN

  !$OMP PARALLEL DO SCHEDULE (STATIC) PRIVATE(ISTA) IF (.FALSE.)
  DO ISTA=1,32
    CALL SPCSI2
    IF (ISTA == 1) CALL LINUX_BIND_DUMP (IRANK, ISIZE)
  ENDDO
  !$OMP END PARALLEL DO

ELSE

  DO ISTA=1,32
    CALL SPCSI2
    IF (ISTA == 1) CALL LINUX_BIND_DUMP (IRANK, ISIZE)
  ENDDO

ENDIF
call get_time(time_end)
write (0,*) "time taken: ",time_end-time_start

END SUBROUTINE

SUBROUTINE SPCSI2

IMPLICIT NONE

INTEGER, PARAMETER :: KFLEVG = 15, KSTA = 1, KEND = 32

REAL(KIND=8) :: ZSPDIVP(KSTA:KEND,KFLEVG)
REAL(KIND=8) :: ZSDIV  (KSTA:KEND,KFLEVG)

INTEGER(KIND=4) :: JLEV, JSP

REAL(KIND=8) :: ZBDT

ZSDIV = 0
ZSPDIVP = 0
ZBDT = 0

!$OMP PARALLEL DO PRIVATE(JSP,JLEV)
  DO JLEV=1,KFLEVG
    DO JSP=KSTA,KEND
      ZSDIV(JSP,JLEV)=ZSPDIVP(JSP,JLEV)-ZBDT*ZSDIV(JSP,JLEV)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO PRIVATE(JSP,JLEV)
  DO JLEV=1,KFLEVG
    DO JSP=KSTA,KEND
      ZSDIV(JSP,JLEV)=ZSPDIVP(JSP,JLEV)-ZBDT*ZSDIV(JSP,JLEV)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO PRIVATE(JSP,JLEV)
  DO JLEV=1,KFLEVG
    DO JSP=KSTA,KEND
      ZSDIV(JSP,JLEV)=ZSPDIVP(JSP,JLEV)-ZBDT*ZSDIV(JSP,JLEV)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO PRIVATE(JSP,JLEV)
  DO JLEV=1,KFLEVG
    DO JSP=KSTA,KEND
      ZSDIV(JSP,JLEV)=ZSPDIVP(JSP,JLEV)-ZBDT*ZSDIV(JSP,JLEV)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO PRIVATE(JSP,JLEV)
  DO JLEV=1,KFLEVG
    DO JSP=KSTA,KEND
      ZSDIV(JSP,JLEV)=ZSPDIVP(JSP,JLEV)-ZBDT*ZSDIV(JSP,JLEV)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO PRIVATE(JSP,JLEV)
  DO JLEV=1,KFLEVG
    DO JSP=KSTA,KEND
      ZSDIV(JSP,JLEV)=ZSPDIVP(JSP,JLEV)-ZBDT*ZSDIV(JSP,JLEV)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO

END SUBROUTINE SPCSI2

END PROGRAM MASTER



